api_platform:
    swagger:
        versions: [3]
    formats:
        jsonapi:  ['application/vnd.api+json']
        jsonld:   ['application/ld+json']
        jsonhal:  ['application/hal+json']
        json:     ['application/json']
        xml:      ['application/xml', 'text/xml']
        yaml:     ['application/x-yaml']
        csv:      ['text/csv']
        html:     ['text/html']